exclude: '/snapshots/'
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: debug-statements
          - id: detect-private-key
          - id: check-added-large-files

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort

    - repo: https://github.com/python/black
      rev: 19.10b0
      hooks:
          - id: black
            language_version: python3.6

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            language_version: python3.6

    - repo: local
      hooks:
          - id: pylint
            name: PyLint
            entry: python -m pylint.__main__ --load-plugins pylint_django --rcfile=.pylintrc
            language: system
            files: \.py$

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
          - id: mypy
