repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: flake8

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.20
      hooks:
          - id: isort

    - repo: https://github.com/python/black
      rev: 19.3b0
      hooks:
          - id: black
            language_version: python3.6

    - repo: local
      hooks:
          - id: pylint
            name: PyLint
            entry: python -m pylint.__main__ --rcfile=.pylintrc
            language: system
            files: \.py$

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.701
      hooks:
          - id: mypy
