# Generated by Django 2.2.8 on 2019-12-23 09:08
# pylint: disable=invalid-name,missing-docstring
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("products", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit or Product Code",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        )
    ]
