# Generated by Django 2.2.8 on 2019-12-23 09:18
# pylint: disable=invalid-name,missing-docstring
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("products", "0003_auto_20191223_1210")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                db_index=True,
                help_text="Stock Keeping Unit or Product Code",
                max_length=255,
                unique=True,
                verbose_name="SKU",
            ),
        )
    ]
