# Generated by Django 2.2 on 2019-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=255,
                                          verbose_name="Name")),
                (
                    "active",
                    models.BooleanField(blank=True,
                                        default=True,
                                        verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=255,
                                          verbose_name="Name")),
                (
                    "active",
                    models.BooleanField(blank=True,
                                        default=True,
                                        verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Modified"),
                ),
                ("name", models.CharField(max_length=255,
                                          verbose_name="Name")),
                (
                    "active",
                    models.BooleanField(blank=True,
                                        default=True,
                                        verbose_name="Active"),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "abstract": False,
            },
        ),
    ]
