# pylint: disable=invalid-name,missing-docstring
# Generated by Django 2.2.3 on 2019-07-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("purchases", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="requisitionlineitem",
            name="item",
            field=models.TextField(verbose_name="Item"),
        )
    ]
