# Generated by Django 2.2.7 on 2019-12-07 21:11
# pylint: disable=invalid-name,missing-docstring
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("products", "0001_initial"), ("purchases", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="requisitionlineitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.Product",
                verbose_name="Product",
            ),
        )
    ]
