# Generated by Django 3.0.7 on 2020-09-04 18:38
# pylint: disable=invalid-name,missing-docstring
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_requisitionlineitem_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requisition", old_name="status", new_name="review_status",
        ),
    ]
