# Generated by Django 3.0.7 on 2020-09-04 18:42
# pylint: disable=invalid-name,missing-docstring
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_auto_20200904_2138"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requisition", old_name="reason", new_name="review_reason",
        ),
    ]
