# Generated by Django 2.2.7 on 2019-12-04 18:33
# pylint: disable=invalid-name,missing-docstring
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("purchases", "0003_requisition_title")]

    operations = [
        migrations.AlterField(
            model_name="requisitionlineitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The price per item",
                max_digits=64,
                verbose_name="Price",
            ),
        )
    ]
